#include "ui.h"

#include "json_utils.h"

#include <stdlib.h>

static const char *HTML_LINES[] = {
    "<!DOCTYPE html>\n",
    "<html lang=\"pt-BR\">\n",
    "<head>\n",
    "  <meta charset=\"UTF-8\">\n",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "  <title>LocalDrop</title>\n",
    "  <style>\n",
    "    :root {\n",
    "      color-scheme: light;\n",
    "      font-family: \"Segoe UI\", sans-serif;\n",
    "      --bg: #eef3f8;\n",
    "      --surface: #ffffff;\n",
    "      --surface-alt: #f8fbff;\n",
    "      --text: #1e293b;\n",
    "      --muted: #64748b;\n",
    "      --primary: #0f62fe;\n",
    "      --primary-dark: #0043ce;\n",
    "      --success: #198754;\n",
    "      --error: #b42318;\n",
    "      --warning: #b54708;\n",
    "      --border: #d7e0ea;\n",
    "    }\n",
    "    * { box-sizing: border-box; }\n",
    "    body { margin: 0; background: radial-gradient(circle at top, #ffffff 0%, var(--bg) 68%); color: var(--text); }\n",
    "    main { max-width: 1100px; margin: 0 auto; padding: 36px 18px 56px; }\n",
    "    h1, h2, h3, p { margin-top: 0; }\n",
    "    .hero { margin-bottom: 18px; }\n",
    "    .hero p { max-width: 60ch; color: var(--muted); }\n",
    "    .grid { display: grid; grid-template-columns: 1.05fr 1.4fr; gap: 18px; align-items: start; }\n",
    "    .section { background: var(--surface); border: 1px solid var(--border); border-radius: 18px; padding: 22px; box-shadow: 0 16px 32px rgba(15, 23, 42, 0.08); }\n",
    "    .section-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; margin-bottom: 16px; }\n",
    "    .muted { color: var(--muted); }\n",
    "    .device-list { display: grid; gap: 12px; }\n",
    "    .device { border: 1px solid var(--border); border-radius: 14px; padding: 16px; background: var(--surface-alt); }\n",
    "    .device p { margin: 4px 0; color: var(--muted); }\n",
    "    .status-pill { display: inline-flex; align-items: center; gap: 6px; border-radius: 999px; padding: 4px 10px; font-size: 0.85rem; background: #e2e8f0; color: var(--text); }\n",
    "    .status-pill.online { background: #dcfce7; color: #166534; }\n",
    "    .status-pill.offline { background: #fee2e2; color: #991b1b; }\n",
    "    .status-pill.paired { background: #dbeafe; color: #1d4ed8; }\n",
    "    .actions { display: flex; gap: 10px; flex-wrap: wrap; margin-top: 12px; }\n",
    "    button { border: none; border-radius: 999px; padding: 10px 18px; font-size: 0.95rem; font-weight: 600; cursor: pointer; background: var(--primary); color: white; }\n",
    "    button:hover { background: var(--primary-dark); }\n",
    "    button.secondary { background: #dce9ff; color: #12316b; }\n",
    "    button.secondary:hover { background: #c5dbff; }\n",
    "    button.warning { background: #fef0c7; color: var(--warning); }\n",
    "    button.warning:hover { background: #fde68a; }\n",
    "    button:disabled { opacity: 0.55; cursor: not-allowed; }\n",
    "    input[type=\"file\"], input[type=\"text\"] { width: 100%; max-width: 100%; padding: 12px 14px; border: 1px solid var(--border); border-radius: 12px; font-size: 1rem; }\n",
    "    .input-row { display: grid; gap: 10px; }\n",
    "    .upload-area { border: 2px dashed #bfd2e7; border-radius: 20px; padding: 24px; background: linear-gradient(180deg, #fbfdff 0%, #f5f9ff 100%); }\n",
    "    .progress { background: #dbe7f3; border-radius: 999px; height: 28px; margin-top: 18px; overflow: hidden; }\n",
    "    .progress-bar { background: linear-gradient(90deg, #0f62fe 0%, #42a5f5 100%); height: 100%; width: 0%; color: white; line-height: 28px; text-align: center; font-size: 0.85rem; transition: width 0.25s ease; }\n",
    "    .hidden { display: none; }\n",
    "    .card-list { display: grid; gap: 14px; }\n",
    "    .auth-lock { border: 1px solid #fed7aa; background: #fff7ed; }\n",
    "    .auth-lock strong { display: block; margin-bottom: 8px; }\n",
    "    .status { min-height: 24px; margin-top: 14px; font-weight: 600; }\n",
    "    .status.success { color: var(--success); }\n",
    "    .status.error { color: var(--error); }\n",
    "    .code-box { display: flex; align-items: baseline; justify-content: space-between; gap: 12px; padding: 16px; border: 1px solid var(--border); border-radius: 16px; background: var(--surface-alt); }\n",
    "    .code-value { font-size: 2rem; font-weight: 700; letter-spacing: 0.2em; }\n",
    "    .locked-note { color: var(--warning); font-weight: 600; }\n",
    "    @media (max-width: 860px) {\n",
    "      .grid { grid-template-columns: 1fr; }\n",
    "      button { width: 100%; }\n",
    "      .actions { flex-direction: column; }\n",
    "      .code-box { flex-direction: column; align-items: flex-start; }\n",
    "    }\n",
    "  </style>\n",
    "</head>\n",
    "<body>\n",
    "  <main>\n",
    "    <section class=\"hero\">\n",
    "      <h1>LocalDrop</h1>\n",
    "      <p>Compartilhamento local com descoberta automatica, destravamento administrativo local e pareamento entre peers antes do envio.</p>\n",
    "    </section>\n",
    "    <div class=\"grid\">\n",
    "      <div class=\"card-list\">\n",
    "        <section class=\"section auth-lock\" id=\"unlockPanel\">\n",
    "          <strong>Destravar interface</strong>\n",
    "          <p class=\"muted\">Use o codigo administrativo mostrado no terminal para autorizar uploads, pareamentos e envios.</p>\n",
    "          <form id=\"unlockForm\" class=\"input-row\">\n",
    "            <input type=\"text\" id=\"adminCodeInput\" name=\"admin_code\" maxlength=\"6\" inputmode=\"numeric\" placeholder=\"Codigo administrativo\">\n",
    "            <button type=\"submit\">Destravar sessao</button>\n",
    "          </form>\n",
    "          <div id=\"unlockStatus\" class=\"status\" aria-live=\"polite\"></div>\n",
    "        </section>\n",
    "        <section class=\"section\" id=\"pairingPanel\">\n",
    "          <div class=\"section-header\">\n",
    "            <div>\n",
    "              <h2>Codigo de pareamento</h2>\n",
    "              <p class=\"muted\">Abra esta secao no dispositivo que vai receber o arquivo e informe o codigo no dispositivo de origem.</p>\n",
    "            </div>\n",
    "            <button id=\"refreshPairingCode\" class=\"secondary\" type=\"button\">Atualizar codigo</button>\n",
    "          </div>\n",
    "          <div class=\"code-box\">\n",
    "            <div>\n",
    "              <div class=\"code-value\" id=\"pairingCodeValue\">------</div>\n",
    "              <div class=\"muted\" id=\"pairingCodeExpiry\">Destrave a interface para gerar um codigo.</div>\n",
    "            </div>\n",
    "            <div class=\"locked-note\" id=\"pairingLockState\">Bloqueado ate a autenticacao local.</div>\n",
    "          </div>\n",
    "        </section>\n",
    "        <section class=\"section\">\n",
    "          <div class=\"section-header\">\n",
    "            <div>\n",
    "              <h2>Receber arquivo neste dispositivo</h2>\n",
    "              <p class=\"muted\">Uploads locais exigem uma sessao administrativa destravada.</p>\n",
    "            </div>\n",
    "          </div>\n",
    "          <div class=\"upload-area\">\n",
    "            <form id=\"uploadForm\" class=\"input-row\" enctype=\"multipart/form-data\">\n",
    "              <input type=\"file\" name=\"file\" id=\"fileInput\" required>\n",
    "              <button type=\"submit\">Enviar para este dispositivo</button>\n",
    "            </form>\n",
    "            <div id=\"progress-container\" class=\"hidden\">\n",
    "              <div class=\"progress\"><div id=\"progress-bar\" class=\"progress-bar\">0%</div></div>\n",
    "            </div>\n",
    "            <div id=\"uploadStatus\" class=\"status\" aria-live=\"polite\"></div>\n",
    "          </div>\n",
    "        </section>\n",
    "      </div>\n",
    "      <section class=\"section\">\n",
    "        <div class=\"section-header\">\n",
    "          <div>\n",
    "            <h2>Dispositivos descobertos</h2>\n",
    "            <p class=\"muted\">Somente peers pareados ficam liberados para envio.</p>\n",
    "          </div>\n",
    "          <button id=\"refreshDevices\" class=\"secondary\" type=\"button\">Atualizar lista</button>\n",
    "        </div>\n",
    "        <div id=\"devices\" class=\"device-list\" aria-live=\"polite\"></div>\n",
    "        <input type=\"file\" id=\"sendFileInput\" class=\"hidden\">\n",
    "      </section>\n",
    "    </div>\n",
    "  </main>\n",
    "  <script>\n",
    "    const initialUiToken = ",
    NULL,
    ";\n",
    "    let uiToken = window.localStorage.getItem('localdropUiToken') || initialUiToken || '';\n",
    "    let selectedDevice = null;\n",
    "    const devicesContainer = document.getElementById('devices');\n",
    "    const sendFileInput = document.getElementById('sendFileInput');\n",
    "    const progressContainer = document.getElementById('progress-container');\n",
    "    const progressBar = document.getElementById('progress-bar');\n",
    "    const uploadStatus = document.getElementById('uploadStatus');\n",
    "    const unlockStatus = document.getElementById('unlockStatus');\n",
    "    const pairingCodeValue = document.getElementById('pairingCodeValue');\n",
    "    const pairingCodeExpiry = document.getElementById('pairingCodeExpiry');\n",
    "    const pairingLockState = document.getElementById('pairingLockState');\n",
    "    function isUnlocked() {\n",
    "      return Boolean(uiToken);\n",
    "    }\n",
    "    function setUiToken(token) {\n",
    "      uiToken = token || '';\n",
    "      if (uiToken) {\n",
    "        window.localStorage.setItem('localdropUiToken', uiToken);\n",
    "      } else {\n",
    "        window.localStorage.removeItem('localdropUiToken');\n",
    "      }\n",
    "      updateAuthState();\n",
    "    }\n",
    "    function setStatus(node, message, type) {\n",
    "      node.className = 'status ' + (type || '');\n",
    "      node.textContent = message || '';\n",
    "    }\n",
    "    function clearElement(node) {\n",
    "      while (node.firstChild) {\n",
    "        node.removeChild(node.firstChild);\n",
    "      }\n",
    "    }\n",
    "    function renderEmptyState(message) {\n",
    "      clearElement(devicesContainer);\n",
    "      const text = document.createElement('p');\n",
    "      text.textContent = message;\n",
    "      devicesContainer.appendChild(text);\n",
    "    }\n",
    "    async function apiFetch(path, options = {}) {\n",
    "      const headers = new Headers(options.headers || {});\n",
    "      if (uiToken) {\n",
    "        headers.set('X-LocalDrop-UI-Token', uiToken);\n",
    "      }\n",
    "      const response = await fetch(path, { ...options, headers });\n",
    "      if ((response.status === 401 || response.status === 403) && uiToken) {\n",
    "        setUiToken('');\n",
    "        setStatus(unlockStatus, 'Sessao expirada. Destrave novamente.', 'error');\n",
    "      }\n",
    "      return response;\n",
    "    }\n",
    "    function updateAuthState() {\n",
    "      const unlocked = isUnlocked();\n",
    "      document.getElementById('unlockPanel').classList.toggle('hidden', unlocked);\n",
    "      pairingLockState.textContent = unlocked ? 'Sessao autenticada. Codigo pronto para uso.' : 'Bloqueado ate a autenticacao local.';\n",
    "      if (!unlocked) {\n",
    "        pairingCodeValue.textContent = '------';\n",
    "        pairingCodeExpiry.textContent = 'Destrave a interface para gerar um codigo.';\n",
    "      }\n",
    "    }\n",
    "    function createBadge(text, className) {\n",
    "      const badge = document.createElement('span');\n",
    "      badge.className = 'status-pill ' + className;\n",
    "      badge.textContent = text;\n",
    "      return badge;\n",
    "    }\n",
    "    async function refreshPairingCode(forceRefresh) {\n",
    "      if (!isUnlocked()) {\n",
    "        return;\n",
    "      }\n",
    "      if (!forceRefresh && pairingCodeValue.textContent !== '------') {\n",
    "        return;\n",
    "      }\n",
    "      const response = await apiFetch('/api/pair/local-code');\n",
    "      const result = await response.json().catch(() => ({}));\n",
    "      if (!response.ok || result.status !== 'ok') {\n",
    "        setStatus(unlockStatus, result.message || 'Falha ao obter codigo de pareamento.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      pairingCodeValue.textContent = result.code || '------';\n",
    "      pairingCodeExpiry.textContent = result.expires_at ? ('Valido ate ' + new Date(result.expires_at * 1000).toLocaleTimeString('pt-BR')) : 'Codigo sem expiracao informada';\n",
    "    }\n",
    "    async function unlockSession(event) {\n",
    "      event.preventDefault();\n",
    "      const adminCode = document.getElementById('adminCodeInput').value.trim();\n",
    "      if (!adminCode) {\n",
    "        setStatus(unlockStatus, 'Informe o codigo administrativo.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      const formData = new FormData();\n",
    "      formData.append('admin_code', adminCode);\n",
    "      const response = await apiFetch('/api/session/unlock', { method: 'POST', body: formData });\n",
    "      const result = await response.json().catch(() => ({}));\n",
    "      if (!response.ok || result.status !== 'ok' || !result.token) {\n",
    "        setStatus(unlockStatus, result.message || 'Nao foi possivel destravar a sessao.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      setUiToken(result.token);\n",
    "      document.getElementById('adminCodeInput').value = '';\n",
    "      setStatus(unlockStatus, 'Sessao destravada com sucesso.', 'success');\n",
    "      await refreshPairingCode(true);\n",
    "      await refreshDevices();\n",
    "    }\n",
    "    async function pairDevice(device) {\n",
    "      if (!isUnlocked()) {\n",
    "        setStatus(unlockStatus, 'Destrave a interface antes de parear peers.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      const pairCode = window.prompt('Digite o codigo de pareamento exibido no dispositivo ' + device.name + ':');\n",
    "      if (!pairCode) {\n",
    "        return;\n",
    "      }\n",
    "      const formData = new FormData();\n",
    "      formData.append('target_ip', device.ip);\n",
    "      formData.append('target_port', String(device.port));\n",
    "      formData.append('target_name', device.name);\n",
    "      formData.append('pair_code', pairCode.trim());\n",
    "      const response = await apiFetch('/api/pair', { method: 'POST', body: formData });\n",
    "      const result = await response.json().catch(() => ({}));\n",
    "      if (!response.ok || result.status !== 'ok') {\n",
    "        window.alert(result.message || 'Falha ao parear com o peer remoto.');\n",
    "        return;\n",
    "      }\n",
    "      window.alert(result.message || ('Peer ' + device.name + ' pareado com sucesso.'));\n",
    "      await refreshDevices();\n",
    "    }\n",
    "    function renderDevice(device) {\n",
    "      const card = document.createElement('article');\n",
    "      card.className = 'device';\n",
    "      const titleRow = document.createElement('div');\n",
    "      titleRow.className = 'section-header';\n",
    "      const title = document.createElement('h3');\n",
    "      title.textContent = device.name;\n",
    "      titleRow.appendChild(title);\n",
    "      const badges = document.createElement('div');\n",
    "      badges.className = 'actions';\n",
    "      badges.appendChild(createBadge(device.active ? 'Online' : 'Offline', device.active ? 'online' : 'offline'));\n",
    "      if (device.paired) {\n",
    "        badges.appendChild(createBadge('Pareado', 'paired'));\n",
    "      }\n",
    "      titleRow.appendChild(badges);\n",
    "      card.appendChild(titleRow);\n",
    "      const address = document.createElement('p');\n",
    "      address.textContent = 'Endereco: ' + device.ip + ':' + device.port;\n",
    "      card.appendChild(address);\n",
    "      const actions = document.createElement('div');\n",
    "      actions.className = 'actions';\n",
    "      const pairButton = document.createElement('button');\n",
    "      pairButton.type = 'button';\n",
    "      pairButton.className = 'secondary';\n",
    "      pairButton.textContent = device.paired ? 'Pareado' : 'Parear';\n",
    "      pairButton.disabled = !isUnlocked() || !device.active || device.paired;\n",
    "      pairButton.addEventListener('click', () => pairDevice(device));\n",
    "      actions.appendChild(pairButton);\n",
    "      const sendButton = document.createElement('button');\n",
    "      sendButton.type = 'button';\n",
    "      sendButton.textContent = 'Enviar arquivo';\n",
    "      sendButton.disabled = !isUnlocked() || !device.active || !device.paired;\n",
    "      sendButton.addEventListener('click', () => {\n",
    "        selectedDevice = device;\n",
    "        sendFileInput.click();\n",
    "      });\n",
    "      actions.appendChild(sendButton);\n",
    "      card.appendChild(actions);\n",
    "      return card;\n",
    "    }\n",
    "    async function refreshDevices() {\n",
    "      try {\n",
    "        const response = await apiFetch('/api/devices');\n",
    "        if (!response.ok) {\n",
    "          throw new Error('Falha ao listar dispositivos');\n",
    "        }\n",
    "        const devices = await response.json();\n",
    "        if (!Array.isArray(devices) || devices.length === 0) {\n",
    "          renderEmptyState('Nenhum dispositivo encontrado no momento.');\n",
    "          return;\n",
    "        }\n",
    "        clearElement(devicesContainer);\n",
    "        devices.forEach((device) => devicesContainer.appendChild(renderDevice(device)));\n",
    "      } catch (error) {\n",
    "        renderEmptyState('Erro ao carregar dispositivos: ' + error.message);\n",
    "      }\n",
    "    }\n",
    "    sendFileInput.addEventListener('change', async (event) => {\n",
    "      const file = event.target.files[0];\n",
    "      if (!file || !selectedDevice) {\n",
    "        return;\n",
    "      }\n",
    "      const formData = new FormData();\n",
    "      formData.append('file', file);\n",
    "      formData.append('target_ip', selectedDevice.ip);\n",
    "      formData.append('target_port', String(selectedDevice.port));\n",
    "      const response = await apiFetch('/api/send', { method: 'POST', body: formData });\n",
    "      const result = await response.json().catch(() => ({}));\n",
    "      if (!response.ok || result.status !== 'ok') {\n",
    "        window.alert(result.message || 'Falha ao iniciar o envio remoto.');\n",
    "      } else {\n",
    "        window.alert(result.message || ('Arquivo enviado para ' + selectedDevice.name));\n",
    "      }\n",
    "      event.target.value = '';\n",
    "      selectedDevice = null;\n",
    "    });\n",
    "    document.getElementById('uploadForm').addEventListener('submit', (event) => {\n",
    "      event.preventDefault();\n",
    "      if (!isUnlocked()) {\n",
    "        setStatus(uploadStatus, 'Destrave a interface antes de enviar arquivos.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      const file = document.getElementById('fileInput').files[0];\n",
    "      if (!file) {\n",
    "        setStatus(uploadStatus, 'Escolha um arquivo para continuar.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      const formData = new FormData();\n",
    "      formData.append('file', file);\n",
    "      progressContainer.classList.remove('hidden');\n",
    "      progressBar.style.width = '0%';\n",
    "      progressBar.textContent = '0%';\n",
    "      setStatus(uploadStatus, '', '');\n",
    "      const request = new XMLHttpRequest();\n",
    "      request.upload.addEventListener('progress', (uploadEvent) => {\n",
    "        if (!uploadEvent.lengthComputable) {\n",
    "          return;\n",
    "        }\n",
    "        const percent = Math.round((uploadEvent.loaded / uploadEvent.total) * 100);\n",
    "        progressBar.style.width = percent + '%';\n",
    "        progressBar.textContent = percent + '%';\n",
    "      });\n",
    "      request.addEventListener('load', () => {\n",
    "        const result = JSON.parse(request.responseText || '{}');\n",
    "        if (request.status === 200) {\n",
    "          setStatus(uploadStatus, result.message || 'Arquivo recebido com sucesso.', 'success');\n",
    "          document.getElementById('fileInput').value = '';\n",
    "        } else {\n",
    "          setStatus(uploadStatus, result.message || 'Falha ao receber arquivo.', 'error');\n",
    "        }\n",
    "        window.setTimeout(() => progressContainer.classList.add('hidden'), 1600);\n",
    "      });\n",
    "      request.addEventListener('error', () => {\n",
    "        setStatus(uploadStatus, 'Falha de conexao com o servidor.', 'error');\n",
    "      });\n",
    "      request.open('POST', '/upload');\n",
    "      if (uiToken) {\n",
    "        request.setRequestHeader('X-LocalDrop-UI-Token', uiToken);\n",
    "      }\n",
    "      request.send(formData);\n",
    "    });\n",
    "    document.getElementById('unlockForm').addEventListener('submit', unlockSession);\n",
    "    document.getElementById('refreshDevices').addEventListener('click', refreshDevices);\n",
    "    document.getElementById('refreshPairingCode').addEventListener('click', () => refreshPairingCode(true));\n",
    "    updateAuthState();\n",
    "    if (isUnlocked()) {\n",
    "      refreshPairingCode(true);\n",
    "    }\n",
    "    refreshDevices();\n",
    "    window.setInterval(refreshDevices, 3000);\n",
    "  </script>\n",
    "</body>\n",
    "</html>\n"
};

char *ui_render_index_page(const char *ui_token) {
    char *page = NULL;
    size_t length = 0;
    size_t capacity = 0;
    size_t index;

    for (index = 0; index < sizeof(HTML_LINES) / sizeof(HTML_LINES[0]); index++) {
        if (HTML_LINES[index] != NULL) {
            if (json_buffer_append(&page, &length, &capacity, HTML_LINES[index]) != 0) {
                free(page);
                return NULL;
            }
            continue;
        }

        if (json_buffer_append(&page, &length, &capacity, "\"") != 0 ||
            json_buffer_append_escaped(&page, &length, &capacity, ui_token ? ui_token : "") != 0 ||
            json_buffer_append(&page, &length, &capacity, "\"") != 0) {
            free(page);
            return NULL;
        }
    }

    return page;
}
