#include "ui.h"

#include "json_utils.h"

#include <stdlib.h>

static const char *HTML_LINES[] = {
    "<!DOCTYPE html>\n",
    "<html lang=\"pt-BR\">\n",
    "<head>\n",
    "  <meta charset=\"UTF-8\">\n",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "  <title>LocalDrop</title>\n",
    "  <style>\n",
    "    :root {\n",
    "      color-scheme: light;\n",
    "      font-family: \"Segoe UI\", sans-serif;\n",
    "      --bg: #eef3f8;\n",
    "      --surface: #ffffff;\n",
    "      --text: #1e293b;\n",
    "      --muted: #64748b;\n",
    "      --primary: #0f62fe;\n",
    "      --primary-dark: #0043ce;\n",
    "      --success: #198754;\n",
    "      --error: #b42318;\n",
    "      --border: #d7e0ea;\n",
    "    }\n",
    "    * { box-sizing: border-box; }\n",
    "    body { margin: 0; background: radial-gradient(circle at top, #ffffff 0%, var(--bg) 70%); color: var(--text); }\n",
    "    main { max-width: 960px; margin: 0 auto; padding: 40px 20px 60px; }\n",
    "    h1 { margin: 0 0 10px; font-size: 2.25rem; }\n",
    "    p { line-height: 1.5; }\n",
    "    .hero { margin-bottom: 24px; }\n",
    "    .section { background: var(--surface); border: 1px solid var(--border); border-radius: 18px; padding: 24px; margin-bottom: 20px; box-shadow: 0 14px 30px rgba(15, 23, 42, 0.08); }\n",
    "    .section-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; margin-bottom: 18px; }\n",
    "    .device-list { display: grid; gap: 12px; }\n",
    "    .device { border: 1px solid var(--border); border-radius: 14px; padding: 16px; background: #f8fbff; }\n",
    "    .device h3 { margin: 0 0 8px; font-size: 1rem; }\n",
    "    .device p { margin: 4px 0; color: var(--muted); }\n",
    "    .actions { display: flex; gap: 10px; flex-wrap: wrap; margin-top: 12px; }\n",
    "    button { border: none; border-radius: 999px; padding: 10px 18px; font-size: 0.95rem; font-weight: 600; cursor: pointer; background: var(--primary); color: white; }\n",
    "    button:hover { background: var(--primary-dark); }\n",
    "    button.secondary { background: #dce9ff; color: #12316b; }\n",
    "    button.secondary:hover { background: #c5dbff; }\n",
    "    button:disabled { cursor: not-allowed; opacity: 0.55; }\n",
    "    .status-pill { display: inline-flex; align-items: center; gap: 6px; border-radius: 999px; padding: 4px 10px; font-size: 0.85rem; background: #e2e8f0; color: var(--text); }\n",
    "    .status-pill.online { background: #dcfce7; color: #166534; }\n",
    "    .status-pill.offline { background: #fee2e2; color: #991b1b; }\n",
    "    .upload-area { border: 2px dashed #bfd2e7; border-radius: 20px; padding: 28px; background: linear-gradient(180deg, #fbfdff 0%, #f5f9ff 100%); text-align: center; }\n",
    "    input[type=\"file\"] { margin: 20px 0; max-width: 100%; }\n",
    "    #status { min-height: 24px; margin-top: 16px; font-weight: 600; }\n",
    "    #status.success { color: var(--success); }\n",
    "    #status.error { color: var(--error); }\n",
    "    .progress { background: #dbe7f3; border-radius: 999px; height: 28px; margin-top: 18px; overflow: hidden; }\n",
    "    .progress-bar { background: linear-gradient(90deg, #0f62fe 0%, #42a5f5 100%); height: 100%; width: 0%; color: white; line-height: 28px; font-size: 0.85rem; transition: width 0.25s ease; }\n",
    "    .hidden { display: none; }\n",
    "    @media (max-width: 720px) {\n",
    "      main { padding: 24px 14px 36px; }\n",
    "      .section { padding: 18px; }\n",
    "      .section-header { align-items: flex-start; }\n",
    "      button { width: 100%; }\n",
    "      .actions { flex-direction: column; }\n",
    "    }\n",
    "  </style>\n",
    "</head>\n",
    "<body>\n",
    "  <main>\n",
    "    <section class=\"hero\">\n",
    "      <h1>LocalDrop</h1>\n",
    "      <p>Transferencia local com descoberta automatica e fluxo de envio entre dispositivos.</p>\n",
    "    </section>\n",
    "    <section class=\"section\">\n",
    "      <div class=\"section-header\">\n",
    "        <div>\n",
    "          <h2>Dispositivos descobertos</h2>\n",
    "          <p>Lista atualizada com peers anunciados na sua rede local.</p>\n",
    "        </div>\n",
    "        <button id=\"refreshDevices\" class=\"secondary\" type=\"button\">Atualizar lista</button>\n",
    "      </div>\n",
    "      <div id=\"devices\" class=\"device-list\" aria-live=\"polite\"></div>\n",
    "    </section>\n",
    "    <section class=\"section\">\n",
    "      <div class=\"upload-area\">\n",
    "        <h2>Receber arquivo neste dispositivo</h2>\n",
    "        <form id=\"uploadForm\" enctype=\"multipart/form-data\">\n",
    "          <input type=\"file\" name=\"file\" id=\"fileInput\" required>\n",
    "          <button type=\"submit\">Enviar para este dispositivo</button>\n",
    "        </form>\n",
    "        <div id=\"progress-container\" class=\"hidden\">\n",
    "          <div class=\"progress\"><div id=\"progress-bar\" class=\"progress-bar\">0%</div></div>\n",
    "        </div>\n",
    "        <div id=\"status\" aria-live=\"polite\"></div>\n",
    "      </div>\n",
    "    </section>\n",
    "    <input type=\"file\" id=\"sendFileInput\" class=\"hidden\">\n",
    "  </main>\n",
    "  <script>\n",
    "    const uiToken = ",
    NULL,
    ";\n",
    "    let selectedDevice = null;\n",
    "    const devicesContainer = document.getElementById('devices');\n",
    "    const sendFileInput = document.getElementById('sendFileInput');\n",
    "    const progressContainer = document.getElementById('progress-container');\n",
    "    const progressBar = document.getElementById('progress-bar');\n",
    "    const statusNode = document.getElementById('status');\n",
    "    function apiFetch(path, options = {}) {\n",
    "      const headers = new Headers(options.headers || {});\n",
    "      if (uiToken) {\n",
    "        headers.set('X-LocalDrop-UI-Token', uiToken);\n",
    "      }\n",
    "      return fetch(path, { ...options, headers });\n",
    "    }\n",
    "    function setStatus(message, type) {\n",
    "      statusNode.className = type || '';\n",
    "      statusNode.textContent = message || '';\n",
    "    }\n",
    "    function clearElement(node) {\n",
    "      while (node.firstChild) {\n",
    "        node.removeChild(node.firstChild);\n",
    "      }\n",
    "    }\n",
    "    function renderEmptyState(message) {\n",
    "      clearElement(devicesContainer);\n",
    "      const text = document.createElement('p');\n",
    "      text.textContent = message;\n",
    "      devicesContainer.appendChild(text);\n",
    "    }\n",
    "    function createStatusPill(device) {\n",
    "      const pill = document.createElement('span');\n",
    "      pill.className = 'status-pill ' + (device.active ? 'online' : 'offline');\n",
    "      pill.textContent = device.active ? 'Online' : 'Offline';\n",
    "      return pill;\n",
    "    }\n",
    "    function renderDevice(device) {\n",
    "      const card = document.createElement('article');\n",
    "      card.className = 'device';\n",
    "      const titleRow = document.createElement('div');\n",
    "      titleRow.className = 'section-header';\n",
    "      const title = document.createElement('h3');\n",
    "      title.textContent = device.name;\n",
    "      titleRow.appendChild(title);\n",
    "      titleRow.appendChild(createStatusPill(device));\n",
    "      card.appendChild(titleRow);\n",
    "      const address = document.createElement('p');\n",
    "      address.textContent = 'Endereco: ' + device.ip + ':' + device.port;\n",
    "      card.appendChild(address);\n",
    "      const actions = document.createElement('div');\n",
    "      actions.className = 'actions';\n",
    "      const sendButton = document.createElement('button');\n",
    "      sendButton.type = 'button';\n",
    "      sendButton.textContent = 'Enviar arquivo';\n",
    "      sendButton.disabled = !device.active;\n",
    "      sendButton.addEventListener('click', () => {\n",
    "        selectedDevice = device;\n",
    "        sendFileInput.click();\n",
    "      });\n",
    "      actions.appendChild(sendButton);\n",
    "      card.appendChild(actions);\n",
    "      return card;\n",
    "    }\n",
    "    async function refreshDevices() {\n",
    "      try {\n",
    "        const response = await apiFetch('/api/devices');\n",
    "        if (!response.ok) {\n",
    "          throw new Error('Falha ao listar dispositivos');\n",
    "        }\n",
    "        const devices = await response.json();\n",
    "        if (!Array.isArray(devices) || devices.length === 0) {\n",
    "          renderEmptyState('Nenhum dispositivo encontrado no momento.');\n",
    "          return;\n",
    "        }\n",
    "        clearElement(devicesContainer);\n",
    "        devices.forEach((device) => {\n",
    "          devicesContainer.appendChild(renderDevice(device));\n",
    "        });\n",
    "      } catch (error) {\n",
    "        renderEmptyState('Erro ao carregar dispositivos: ' + error.message);\n",
    "      }\n",
    "    }\n",
    "    sendFileInput.addEventListener('change', async (event) => {\n",
    "      const file = event.target.files[0];\n",
    "      if (!file || !selectedDevice) {\n",
    "        return;\n",
    "      }\n",
    "      const formData = new FormData();\n",
    "      formData.append('file', file);\n",
    "      formData.append('target_ip', selectedDevice.ip);\n",
    "      formData.append('target_port', String(selectedDevice.port));\n",
    "      try {\n",
    "        const response = await apiFetch('/api/send', { method: 'POST', body: formData });\n",
    "        const result = await response.json().catch(() => ({}));\n",
    "        if (!response.ok || result.status !== 'ok') {\n",
    "          throw new Error(result.message || 'Erro ao enviar arquivo');\n",
    "        }\n",
    "        window.alert(result.message || ('Arquivo enviado para ' + selectedDevice.name));\n",
    "      } catch (error) {\n",
    "        window.alert(error.message);\n",
    "      } finally {\n",
    "        event.target.value = '';\n",
    "        selectedDevice = null;\n",
    "      }\n",
    "    });\n",
    "    document.getElementById('uploadForm').addEventListener('submit', (event) => {\n",
    "      event.preventDefault();\n",
    "      const file = document.getElementById('fileInput').files[0];\n",
    "      if (!file) {\n",
    "        setStatus('Escolha um arquivo para continuar.', 'error');\n",
    "        return;\n",
    "      }\n",
    "      const formData = new FormData();\n",
    "      formData.append('file', file);\n",
    "      progressContainer.classList.remove('hidden');\n",
    "      progressBar.style.width = '0%';\n",
    "      progressBar.textContent = '0%';\n",
    "      setStatus('', '');\n",
    "      const request = new XMLHttpRequest();\n",
    "      request.upload.addEventListener('progress', (uploadEvent) => {\n",
    "        if (!uploadEvent.lengthComputable) {\n",
    "          return;\n",
    "        }\n",
    "        const percent = Math.round((uploadEvent.loaded / uploadEvent.total) * 100);\n",
    "        progressBar.style.width = percent + '%';\n",
    "        progressBar.textContent = percent + '%';\n",
    "      });\n",
    "      request.addEventListener('load', () => {\n",
    "        const result = JSON.parse(request.responseText || '{}');\n",
    "        if (request.status === 200) {\n",
    "          setStatus(result.message || 'Arquivo recebido com sucesso.', 'success');\n",
    "          document.getElementById('fileInput').value = '';\n",
    "        } else {\n",
    "          setStatus(result.message || 'Falha ao receber arquivo.', 'error');\n",
    "        }\n",
    "        setTimeout(() => progressContainer.classList.add('hidden'), 1500);\n",
    "      });\n",
    "      request.addEventListener('error', () => {\n",
    "        setStatus('Falha de conexao com o servidor.', 'error');\n",
    "      });\n",
    "      request.open('POST', '/upload');\n",
    "      if (uiToken) {\n",
    "        request.setRequestHeader('X-LocalDrop-UI-Token', uiToken);\n",
    "      }\n",
    "      request.send(formData);\n",
    "    });\n",
    "    document.getElementById('refreshDevices').addEventListener('click', refreshDevices);\n",
    "    refreshDevices();\n",
    "    window.setInterval(refreshDevices, 3000);\n",
    "  </script>\n",
    "</body>\n",
    "</html>\n"
};

char *ui_render_index_page(const char *ui_token) {
    char *page = NULL;
    size_t length = 0;
    size_t capacity = 0;
    size_t index;

    for (index = 0; index < sizeof(HTML_LINES) / sizeof(HTML_LINES[0]); index++) {
        if (HTML_LINES[index] != NULL) {
            if (json_buffer_append(&page, &length, &capacity, HTML_LINES[index]) != 0) {
                free(page);
                return NULL;
            }
            continue;
        }

        if (json_buffer_append(&page, &length, &capacity, "\"") != 0 ||
            json_buffer_append_escaped(&page, &length, &capacity, ui_token ? ui_token : "") != 0 ||
            json_buffer_append(&page, &length, &capacity, "\"") != 0) {
            free(page);
            return NULL;
        }
    }

    return page;
}
